### PR TITLE
Add consistent vendor prefixes

### PR DESCRIPTION
**Pull request by ghost**
Following #14 I've added consistent vendor prefixes to required features.

Since you're working on Firefox version, I jumped ahead and added `-moz-` prefixes as well, but happy to take them out if required.

Few notes:

* Removed `shape-inside` property since it has been deferred to [CSS Shapes Level 2](https://drafts.csswg.org/css-shapes-2/) and implementations for it have been withdrawn.
* Updated `transition` properties to only include the necessary. No longhand properties have effect unless `transition-property` is defined (same as `animation` with `animation-name`).

Cheers

### CODE REVIEW

**Comment by keithclark** [comment]
Thanks for looking into this.

For the moment I'd like to keep `-moz-` prefixes out of the source. They can be added and tested as part of the Firefox support work.

Regarding `shape-inside`, I'm not up to speed with the CSS Shapes Module - do you have a reference detailing the implementation withdrawal?

The extra `transition` rules were added in #7. I found they can be triggered without setting a `transition-property` because the [initial value](https://www.w3.org/TR/css-transitions-1/#propdef-transition-property) of that property is `all`, therefore setting `transition-duration: 5s` is enough.

`transition-delay` was also disabled because you can trigger transitions by setting this value and omitting the other properties. Doing so will cause a transition to happen instantly (because `transition-duration` defaults to 0s`) after the specific delay has passed.

I think it's time to create a web page that can be used to test these cases — I'll look into that.

**Comment by keithclark** [comment]
I've created #17 which contains the commits for reorganising the repo. I'll get that merged soon and then work on getting the browser tests included. Once that's done we can create test cases for any prefixes that were missed and then look to apply your changes to fix them.

**Comment by keithclark** [comment]
I've added the test page and [created a PR for it](https://github.com/keithclark/css-feature-toggle-devtools-extension/pull/18). It would be good create test cases for the missing vendor prefixes you've found.

**Comment by keithclark** [comment]
Test page is now merged into master.

**Comment by keithclark** [comment]
@indrekpaas Because of the repo structure changes, this PR is going to need some work before it's ready to review/merge. Do you have time to get this in order? If not, I can quickly branch off master and make the necessary changes to each toggle.

**Comment by indrekpaas** [comment]
@keithclark would love to get this out, but unfortunately I'm tight on time right now. Feel free to branch off and close this PR to move forward. Cheers

**Comment by keithclark** [comment]
No problem. I'll make the relevant changes in another branch.

**Pull request closed without merging**
